### ISSUE TITLE
Watermark doesn't update after changing settings

### ISSUE THREAD

**Issue by michael-hawker** [mrlacey/VSWaterMark#1]
Not sure if this is related to your other issue you're fixing, but I noticed after I change the settings in the Options window it doesn't update until I open a new file or resize.

Is this something you can detect?

**Comment by michael-hawker** [comment]
Or is it possible to just live-update it in the background behind the options dialog as options are changed? 😉

**Comment by mrlacey** [comment]
working on it ;)

**Comment by mrlacey** [comment]
Version 1.1 is now in the marketplace. It includes all the ways I can think of to try and ensure the watermark is shown and updated as soon as possible and without the need to reopen or resize anything.

It's not perfect but this appears to be due to some documents incorrectly reporting (or calculating) their viewports once created and so the watermark is positioned where it can't be seen. This doesn't cause a problem if the watermark is in the top left but that's probably the least desirable place to put it.

**Comment by mrlacey** [comment]
I don't think there's anything else I can do here for now.
